name: docker
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    branches:
      - master
  pull_request:
env:
  DOCKER_LOCATION: .
  DOCKER_REPO_BASE: ghcr.io/bsgrigorov/github-releases-notifier
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get docker version
        id: vars
        working-directory: ${{ env.DOCKER_LOCATION }}
        run: |
          if [ ! -f "version.txt" ]; then
            echo "version.txt does not exist"
            exit 1
          fi
          VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      - name: docker build
        working-directory: ${{ env.DOCKER_LOCATION }}
        run: |
          docker build -t "${{ env.DOCKER_REPO_BASE}}:${{ env.IMAGE_TAG }}" . -f "./Dockerfile"

      - name: docker push
        # if: github.event_name == 'push'
        working-directory: ${{ env.DOCKER_LOCATION }}
        run: |
          docker push ${{ env.DOCKER_REPO_BASE}}:${{ env.IMAGE_TAG }}

      - name: Summary
        # if: github.event_name == 'push'
        run: |
          echo '### Docker Build' >> $GITHUB_STEP_SUMMARY
          echo 'Pushed image ${{ env.DOCKER_REPO_BASE}}:${{ env.IMAGE_TAG }}' >> $GITHUB_STEP_SUMMARY
